version: "3.9"

services:
  meetupbot:
    container_name: meetup_bot-cont
    image: meetup_bot
    tty: false               # false for `entrypoint` in Dockerfile
    stdin_open: false        # false for `entrypoint` in Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/home/appuser/app
    ports:
      - 80:3000
    build:
      context: ./
      dockerfile: ./Dockerfile

  redis:
    container_name: redis-cont
    image: "redis:alpine"
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
    env_file:
      - ./.env
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - 6379:6379
    volumes:
      # save redisearch data to your current working directory
      - ./redis-data:/data
      - ./redis.conf:/redis.conf:ro
    command: [ "redis-server", "/redis.conf" ]

  # redis db visualization dashboard
  redisinsight:
    container_name: redisinsight-cont
    image: redislabs/redisinsight
    tty: true
    stdin_open: true
    depends_on:
      - redis
    ports:
      - 8001:8001
    volumes:
      - ./redis-insight:/db

volumes:
  redis-data:
    driver: local

networks:
  default:
    driver: bridge
