services:
  meetup-bot:
    # container_name: meetup-bot
    image: ghcr.io/pythoninthegrass/meetup-bot
    build:
      context: .
      dockerfile: Dockerfile.web
    platform: ${PLATFORM:-linux/amd64}  # linux/amd64, linux/arm64/v8
    tty: false                          # false for `entrypoint` in Dockerfile
    stdin_open: false                   # false for `entrypoint` in Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - ${PORT:-3100}:3100
    networks:
      - default

networks:
  default:
    driver: bridge
