[tool.poetry]
name = "meetup_bot"
version = "0.1.0"
description = ""
authors = ["pythoninthegrass <4097471+pythoninthegrass@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.4"
aiohttp = "^3.8.1"
arrow = "^1.2.2"
bs4 = "^0.0.1"
click = "^8.1.2"
fastapi = "^0.75.2"
icecream = "^2.1.2"
orjson = "^3.6.8"
pandas = "^1.4.2"
python-decouple = "^3.6"
requests = "^2.27.1"
requests-cache = "^0.9.3"
slack-sdk = "^3.15.2"
tqdm = "^4.64.0"
uvicorn = "^0.17.6"
aiofile = "^3.7.4"
playwright = "^1.21.0"
requests-oauthlib = "^1.3.1"
Authlib = "^1.0.1"
httpx = "^0.22.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
