[tool.poetry]
name = "meetup_bot"
version = "0.1.0"
description = ""
authors = ["pythoninthegrass <4097471+pythoninthegrass@users.noreply.github.com>"]
readme = "README.md"

[[tool.poetry.source]]
name = "test-pypi"
url = "https://test.pypi.org/simple"
secondary = true

[tool.poetry.dependencies]
python = "^3.10"
arrow = "^1.2.2"
colorama = "^0.4.5"
exceptiongroup = "^1.0.0-rc.9"
fastapi = ">=0.82.0"
gunicorn = "^20.1.0"
pandas = "^1.4.2"
pony = "^0.7.16"
PyJWT = {extras = ["crypto"], version = "^2.5.0"}
python-decouple = "^3.6"
requests = "^2.27.1"
requests-cache = "^0.9.3"
slack-sdk = "^3.17.2"
uvicorn = "^0.18.2"
Jinja2 = "^3.1.2"
python-multipart = "^0.0.5"
jose = "^1.0.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
APScheduler = "^3.9.1"
# psycopg2-binary = {version = "^2.9.3", source = "test-pypi"}  # M1
psycopg2-binary = "^2.9.3"

[tool.poetry.dev-dependencies]
icecream = "^2.1.3"
ipython = "^8.4.0"
rich = "^12.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
