[tool.poetry]
name = "meetup_bot"
version = "1.1.0"
description = "Use Meetup Pro API to send Slack messages before events occur."
authors = ["pythoninthegrass <4097471+pythoninthegrass@users.noreply.github.com>"]
readme = "README.md"
license = "Unlicense"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
arrow = "^1.3.0"
bcrypt = "4.0.1"
colorama = "^0.4.5"
exceptiongroup = "^1.2.2"
fastapi = ">=0.112.1"
gunicorn = "^20.1.0"
icecream = "^2.1.3"
Jinja2 = "^3.1.4"
jose = "^1.0.0"
numpy = "1.26.4"
pandas = "^1.5.3"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pony = "^0.7.16"
psycopg2-binary = "^2.9.9"
PyJWT = {extras = ["crypto"], version = "^2.9.0"}
python-decouple = "^3.8"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
python-multipart = "^0.0.9"
requests = "^2.32.3"
requests-cache = "^1.2.1"
slack-sdk = "^3.31.0"
uvicorn = "^0.29.0"
wheel = "^0.43.0"

[tool.poetry.group.dev.dependencies]
APScheduler = "^3.10.4"
ipython = "^8.26.0"
playwright = "^1.46.0"
poetry-plugin-export = "^1.8.0"
poetry-plugin-up = "^0.7.1"
pyclean = "^3.0.0"
pytest = "^8.3.2"
pytest-asyncio = "^0.23.7"
pytest-cov = "^5.0.0"
pytest-datafiles = "^3.0.0"
pytest-xdist = "^3.6.1"
requests-mock = "^1.12.1"
rich = "^13.7.1"
ruff = "^0.6.1"

[tool.ruff]
# Black (default: 88)
line-length = 130

# Assume Python 3.11.
target-version = "py311"

[tool.ruff.lint]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F"]
ignore = []
# Skip unused variable rules
extend-ignore = ["D203", "E203", "E251", "E266", "E401", "E402", "E501", "F401", "F403", "F405"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    "dist",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    "__pycache__",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "qa: marks tests as qa (deselect with '-m \"not qa\"')",
]
testpaths = ["tests"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
