[tool.poetry]
name = "meetup_bot"
version = "1.0.0"
description = ""
authors = ["pythoninthegrass <4097471+pythoninthegrass@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
arrow = "^1.2.2"
colorama = "^0.4.5"
exceptiongroup = "^1.0.0-rc.9"
fastapi = ">=0.85.0"
gunicorn = "^20.1.0"
icecream = "^2.1.3"
Jinja2 = "^3.1.2"
jose = "^1.0.0"
pandas = "^1.5.3"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pony = "^0.7.16"
psycopg2-binary = "^2.9.4"
PyJWT = {extras = ["crypto"], version = "^2.5.0"}
python-decouple = "^3.6"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
python-multipart = "^0.0.5"
requests = "^2.27.1"
requests-cache = "^1.0.1"
slack-sdk = "^3.19.1"
uvicorn = "^0.20.0"
wheel = "^0.40.0"

[tool.poetry.group.dev.dependencies]
APScheduler = "^3.9.1"
ipython = "^8.4.0"
playwright = "^1.27.1"
pytest = "^7.1.3"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.0.0"
pytest-datafiles = "^3.0.0"
pytest-xdist = "^3.2.1"
requests-mock = "^1.10.0"
rich = "^13.3.4"
ruff = "^0.0.270"

[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F"]
ignore = []
# Skip unused variable rules
extend-ignore = ["D203", "E203", "E251", "E266", "E401", "E402", "E501", "F401", "F403", "F405"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    "dist",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    "__pycache__",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Black (default: 88)
line-length = 130

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11.
target-version = "py311"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
