[tool.poetry]
name = "meetup_bot"
version = "1.0.0"
description = ""
authors = ["pythoninthegrass <4097471+pythoninthegrass@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.9"
arrow = "^1.2.2"
colorama = "^0.4.5"
exceptiongroup = "^1.0.0-rc.9"
fastapi = ">=0.85.0"
gunicorn = "^20.1.0"
icecream = "^2.1.3"
Jinja2 = "^3.1.2"
jose = "^1.0.0"
pandas = "^1.5.3"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pony = "^0.7.16"
psycopg2-binary = "^2.9.4"
PyJWT = {extras = ["crypto"], version = "^2.5.0"}
python-decouple = "^3.6"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
python-multipart = "^0.0.5"
requests = "^2.27.1"
requests-cache = "^0.9.8"
slack-sdk = "^3.19.1"
uvicorn = "^0.20.0"

[tool.poetry.group.dev.dependencies]
APScheduler = "^3.9.1"
ipython = "^8.4.0"
playwright = "^1.27.1"
pytest = "^7.1.3"
pytest-asyncio = "^0.19.0"
pytest-mock = "^3.10.0"
pytest-xdist = "^3.2.0"
rich = "^12.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
