[tool.poetry]
name = "meetup_bot"
version = "0.1.0"
description = ""
authors = ["pythoninthegrass <4097471+pythoninthegrass@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.6"
arrow = "^1.2.2"
Authlib = "^1.0.1"
fastapi = ">=0.79.0"
gunicorn = "^20.1.0"
pandas = "^1.4.2"
playwright = "^1.22.0"
PyJWT = {extras = ["crypto"], version = "^2.4.0"}
python-decouple = "^3.6"
python-on-whales = "^0.51.0"
redis = "^4.3.1"
requests = "^2.27.1"
requests-cache = "^0.9.3"
slack-sdk = "^3.17.2"
uvicorn = "^0.18.2"
python-multipart = "^0.0.5"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
fastapi-cache2 = {extras = ["redis"], version = "^0.1.9"}
oauthlib = "^3.2.0"
requests-oauthlib = "^1.3.1"
social-auth-core = "^4.3.0"
httpx-oauth = "^0.9.1"
fastapi-users = {extras = ["redis"], version = "^10.1.5"}

[tool.poetry.dev-dependencies]
icecream = "^2.1.3"
ipython = "^8.4.0"
Markdown = "^3.4.1"
rich = "^12.5.1"
rocketry = "^2.2.0"
tinydb = "^4.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
