[tool.poetry]
name = "meetup_bot"
version = "0.1.0"
description = ""
authors = ["pythoninthegrass <4097471+pythoninthegrass@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.6"
arrow = "^1.2.2"
fastapi = ">=0.79.0"
gunicorn = "^20.1.0"
pandas = "^1.4.2"
python-decouple = "^3.6"
requests = "^2.27.1"
requests-cache = "^0.9.3"
slack-sdk = "^3.17.2"
uvicorn = "^0.18.2"
pony = "^0.7.16"
colorama = "^0.4.5"

[tool.poetry.dev-dependencies]
icecream = "^2.1.3"
ipython = "^8.4.0"
rich = "^12.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
