[tool.poetry]
name = "meetup_bot"
version = "0.1.0"
description = ""
authors = ["pythoninthegrass <4097471+pythoninthegrass@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.5"
arrow = "^1.2.2"
Authlib = "^1.0.1"
fastapi = ">=0.79.0"
pandas = "^1.4.2"
playwright = "^1.22.0"
PyJWT = {extras = ["crypto"], version = "^2.4.0"}
python-decouple = "^3.6"
python-on-whales = "^0.51.0"
redis = "^4.3.1"
requests = "^2.27.1"
requests-cache = "^0.9.3"
slack-sdk = "^3.17.2"
uvicorn = "^0.18.2"

[tool.poetry.dev-dependencies]
icecream = "^2.1.3"
ipython = "^8.4.0"
Markdown = "^3.4.1"
rich = "^12.5.1"
rocketry = "^2.2.0"
tinydb = "^4.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
