version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

dotenv: ['./app/.env']

env:
  TLD: "{{.ROOT_DIR}}"
  APP:
    sh: echo "${APP_NAME:-meetup_bot}"
  SCRIPT:
    sh: "echo ${SCRIPT:-scheduler.sh}"

vars:

includes:
  docker:
    taskfile: ./taskfiles/docker.yml
  heroku:
    taskfile: ./taskfiles/heroku.yml
  uv:
    taskfile: ./taskfiles/uv.yml

tasks:
  print:
    - |
      echo -e "TLD:\t\t$TLD"
      echo -e "APP:\t\t{{.APP}}"
      echo -e "BUILD:\t\t{{.BUILD}}"
      echo -e "COMPOSE_FILE:\t{{.COMPOSE_FILE}}"
      echo -e "DOCKERFILE:\t{{.DOCKERFILE}}"
      echo -e "HEROKU_APP:\t{{.HEROKU_APP}}"
      echo -e "PLATFORM:\t{{.PLATFORM}}"
      echo -e "POETRY:\t\t{{.POETRY}}"
      echo -e "PY_VER:\t\t{{.PY_VER}}"
      echo -e "SCRIPT:\t\t{{.SCRIPT}}"
      echo -e "REGISTRY:\t$REGISTRY"
      echo -e "SERVICE:\t{{.SERVICE}}"
      echo -e "TAG:\t\t${TAG}"
      echo -e "USER_NAME:\t$USER_NAME"
      echo -e "UNAME:\t\t$UNAME"

  default:
    desc: "Default task"
    cmds:
      - task --list

  install:
    desc: "Install project dependencies"
    cmds:
      - |
        {{.INSTALL}} {{.CLI_ARGS}}

  pre-commit:
    desc: "Run pre-commit hooks"
    cmds:
      - pre-commit run --all-files

  lint:
    desc: "Run linters"
    cmds:
      - poetry run ruff check --fix --respect-gitignore

  format:
    desc: "Run formatters"
    cmds:
      - poetry run ruff format --respect-gitignore

  test:
    desc: "Run tests"
    cmds:
      - poetry run pytest

  pyclean:
    desc: "Remove .pyc and __pycache__"
    cmds:
      - |
        args=(
          .
          --debris
          --verbose
          -i .devbox
        )
        case "{{.CLI_ARGS}}" in
          dry-run)
            poetry run pyclean "${args[@]}" --dry-run
            ;;
          *)
            poetry run pyclean "${args[@]}"
            ;;
        esac

  checkbash:
    desc: "Check bash scripts"
    cmds:
      - checkbashism -x {{.TLD}}/app/*.sh

  update-deps:
    desc: "Update dependencies"
    cmds:
      - |
        poetry cache clear --all pypi --no-ansi
        poetry update --lock --no-ansi

  export-reqs:
    desc: "Export requirements.txt"
    summary: |
      Export the project dependencies to a requirements.txt file.
    cmds:
      - |
        poetry export -f requirements.txt \
          --output {{.TLD}}/requirements.txt \
          --without-hashes \
          --no-ansi
    ignore_error: true
