apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetup_bot
  labels:
    app: meetup_bot
spec:
  selector:
    matchLabels:
      app: meetup_bot
  template:
    metadata:
      labels:
        app: meetup_bot
    spec:
      containers:
        - name: meetup_bot
          image: meetup-bot
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
