name: Run pytest in Docker

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.py'
  pull_request:
    branches:
      - main
      - master
    paths:
      - '**/*.py'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11.9-slim-bullseye
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        apt-get -qq update \
        && apt-get -qq install \
          --no-install-recommends -y \
          curl \
          gcc \
          git \
          python3-dev \
        && rm -rf /var/lib/apt/lists/*

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip pytest
        python -m pip install -r requirements.txt

    - name: Run pytest
      run: pytest -s
